// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using p3_backend.Models;

#nullable disable

namespace p3_backend.Migrations
{
    [DbContext(typeof(P3MyImage3Context))]
    [Migration("20260327121031_AddVnPayAndPaymentTransaction")]
    partial class AddVnPayAndPaymentTransaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("p3_backend.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("AdminId")
                        .HasName("PK__Admins__43AA4141082751F8");

                    b.HasIndex(new[] { "Username" }, "UQ__Admins__F3DBC57220EB5890")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("p3_backend.Models.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("f_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("l_name");

                    b.Property<string>("PNo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("p_no");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("CustId")
                        .HasName("PK__Customer__A1B71F9008AF352D");

                    b.HasIndex(new[] { "Email" }, "UQ__Customer__AB6E6164346F7110")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__Customer__F3DBC5724C68D63C")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("p3_backend.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustId")
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    b.Property<string>("FolderName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("folder_name")
                        .HasComputedColumnSql("('folder_'+right('0000'+CONVERT([varchar](4),[order_id]),(4)))", true);

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("order_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<int?>("ProcessedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("processed_by_admin_id");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("shipping_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("total_price");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__465962292ED791DD");

                    b.HasIndex("CustId");

                    b.HasIndex("ProcessedByAdminId");

                    b.HasIndex(new[] { "FolderName" }, "UQ__Orders__3AFC5A9105B1ACE4")
                        .IsUnique()
                        .HasFilter("[folder_name] IS NOT NULL");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("p3_backend.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_detail_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<decimal?>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)")
                        .HasColumnName("line_total")
                        .HasComputedColumnSql("([quantity]*[price_per_copy])", true);

                    b.Property<string>("NoteToAdmin")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("note_to_admin");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int")
                        .HasColumnName("photo_id");

                    b.Property<decimal>("PricePerCopy")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price_per_copy");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("SizeId")
                        .HasColumnType("int")
                        .HasColumnName("size_id");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__3C5A4080731C6E7C");

                    b.HasIndex("OrderId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("SizeId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("p3_backend.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("payment_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("payment_status");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__ED1FC9EA0798E46A");

                    b.HasIndex(new[] { "OrderId" }, "UQ__Payments__465962282B0C99B1")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("p3_backend.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("transaction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 0)")
                        .HasColumnName("amount");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TxnRef")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("txn_ref");

                    b.Property<string>("VnpTransactionNo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vnp_transaction_no");

                    b.HasKey("TransactionId");

                    b.HasIndex("OrderId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("p3_backend.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("photo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhotoId"));

                    b.Property<int>("CustId")
                        .HasColumnType("int")
                        .HasColumnName("cust_id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("file_path");

                    b.Property<DateTime>("UploadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("upload_date")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("PhotoId")
                        .HasName("PK__Photos__CB48C83D07463E73");

                    b.HasIndex("CustId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("p3_backend.Models.PrintSize", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("size_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_available");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("price");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("size_name");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("SizeId")
                        .HasName("PK__PrintSiz__0DCACE319866020C");

                    b.HasIndex("TemplateId");

                    b.ToTable("PrintSizes");
                });

            modelBuilder.Entity("p3_backend.Models.ProductGallery", b =>
                {
                    b.Property<int>("GalleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gallery_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GalleryId"));

                    b.Property<string>("Caption")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("caption");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    b.HasKey("GalleryId")
                        .HasName("PK__ProductG__43D54A71596AAEB7");

                    b.HasIndex("TemplateId");

                    b.ToTable("ProductGallery", (string)null);
                });

            modelBuilder.Entity("p3_backend.Models.ProductTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("template_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("details");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LeadTime")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("2-3 ngày")
                        .HasColumnName("lead_time");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("template_name");

                    b.HasKey("TemplateId")
                        .HasName("PK__ProductT__BE44E079598D3B26");

                    b.ToTable("ProductTemplates");
                });

            modelBuilder.Entity("p3_backend.Models.Order", b =>
                {
                    b.HasOne("p3_backend.Models.Customer", "Cust")
                        .WithMany("Orders")
                        .HasForeignKey("CustId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Customers");

                    b.HasOne("p3_backend.Models.Admin", "ProcessedByAdmin")
                        .WithMany("Orders")
                        .HasForeignKey("ProcessedByAdminId")
                        .HasConstraintName("FK_Orders_Admins");

                    b.Navigation("Cust");

                    b.Navigation("ProcessedByAdmin");
                });

            modelBuilder.Entity("p3_backend.Models.OrderDetail", b =>
                {
                    b.HasOne("p3_backend.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Orders");

                    b.HasOne("p3_backend.Models.Photo", "Photo")
                        .WithMany("OrderDetails")
                        .HasForeignKey("PhotoId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Photos");

                    b.HasOne("p3_backend.Models.PrintSize", "Size")
                        .WithMany("OrderDetails")
                        .HasForeignKey("SizeId")
                        .HasConstraintName("FK_OrderDetails_PrintSizes");

                    b.Navigation("Order");

                    b.Navigation("Photo");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("p3_backend.Models.Payment", b =>
                {
                    b.HasOne("p3_backend.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("p3_backend.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("p3_backend.Models.PaymentTransaction", b =>
                {
                    b.HasOne("p3_backend.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PaymentTransactions_Orders");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("p3_backend.Models.Photo", b =>
                {
                    b.HasOne("p3_backend.Models.Customer", "Cust")
                        .WithMany("Photos")
                        .HasForeignKey("CustId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Photos_Customers");

                    b.Navigation("Cust");
                });

            modelBuilder.Entity("p3_backend.Models.PrintSize", b =>
                {
                    b.HasOne("p3_backend.Models.ProductTemplate", "Template")
                        .WithMany("PrintSizes")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PrintSizes_ProductTemplates");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("p3_backend.Models.ProductGallery", b =>
                {
                    b.HasOne("p3_backend.Models.ProductTemplate", "Template")
                        .WithMany("ProductGalleries")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductGallery_ProductTemplates");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("p3_backend.Models.Admin", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("p3_backend.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Photos");
                });

            modelBuilder.Entity("p3_backend.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("p3_backend.Models.Photo", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("p3_backend.Models.PrintSize", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("p3_backend.Models.ProductTemplate", b =>
                {
                    b.Navigation("PrintSizes");

                    b.Navigation("ProductGalleries");
                });
#pragma warning restore 612, 618
        }
    }
}
